# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_ruya.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(430, 140, 345, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(430, 100, 345, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(430, 180, 345, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_23.setFrameShape(QtWidgets.QFrame.Box)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setFrameShape(QtWidgets.QFrame.Box)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_25.setFrameShape(QtWidgets.QFrame.Box)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(430, 220, 345, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_28.setFrameShape(QtWidgets.QFrame.Box)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_29.setFrameShape(QtWidgets.QFrame.Box)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_30.setFrameShape(QtWidgets.QFrame.Box)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_6.addWidget(self.label_30)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(430, 260, 345, 31))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_31.setFrameShape(QtWidgets.QFrame.Box)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_7.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_32.setFrameShape(QtWidgets.QFrame.Box)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_7.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_33.setFrameShape(QtWidgets.QFrame.Box)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_7.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_34.setFrameShape(QtWidgets.QFrame.Box)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_7.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_7.addWidget(self.label_35)
        self.layoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(430, 300, 345, 31))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_36.setFrameShape(QtWidgets.QFrame.Box)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_8.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_8.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_8.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_39.setFrameShape(QtWidgets.QFrame.Box)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_8.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_40.setFrameShape(QtWidgets.QFrame.Box)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.label_40)
        self.layoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(430, 340, 271, 31))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_41.setFrameShape(QtWidgets.QFrame.Box)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_9.addWidget(self.label_41)
        self.returntotalCHO = QtWidgets.QLabel(self.layoutWidget_7)
        self.returntotalCHO.setFrameShape(QtWidgets.QFrame.Box)
        self.returntotalCHO.setAlignment(QtCore.Qt.AlignCenter)
        self.returntotalCHO.setObjectName("returntotalCHO")
        self.horizontalLayout_9.addWidget(self.returntotalCHO)
        self.returntotalProtein = QtWidgets.QLabel(self.layoutWidget_7)
        self.returntotalProtein.setFrameShape(QtWidgets.QFrame.Box)
        self.returntotalProtein.setAlignment(QtCore.Qt.AlignCenter)
        self.returntotalProtein.setObjectName("returntotalProtein")
        self.horizontalLayout_9.addWidget(self.returntotalProtein)
        self.returntotalYag = QtWidgets.QLabel(self.layoutWidget_7)
        self.returntotalYag.setFrameShape(QtWidgets.QFrame.Box)
        self.returntotalYag.setAlignment(QtCore.Qt.AlignCenter)
        self.returntotalYag.setObjectName("returntotalYag")
        self.horizontalLayout_9.addWidget(self.returntotalYag)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(500, 60, 345, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 410, 261, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.returnHarrisPAL = QtWidgets.QLabel(self.widget)
        self.returnHarrisPAL.setGeometry(QtCore.QRect(0, 10, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.returnHarrisPAL.setFont(font)
        self.returnHarrisPAL.setFrameShape(QtWidgets.QFrame.Box)
        self.returnHarrisPAL.setObjectName("returnHarrisPAL")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.returnSchofield = QtWidgets.QLabel(self.tab_2)
        self.returnSchofield.setGeometry(QtCore.QRect(0, 10, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.returnSchofield.setFont(font)
        self.returnSchofield.setFrameShape(QtWidgets.QFrame.Box)
        self.returnSchofield.setObjectName("returnSchofield")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.returnWHO = QtWidgets.QLabel(self.tab)
        self.returnWHO.setGeometry(QtCore.QRect(0, 10, 251, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.returnWHO.setFont(font)
        self.returnWHO.setFrameShape(QtWidgets.QFrame.Box)
        self.returnWHO.setObjectName("returnWHO")
        self.tabWidget.addTab(self.tab, "")
        self.btnHesapla = QtWidgets.QPushButton(self.centralwidget)
        self.btnHesapla.setGeometry(QtCore.QRect(50, 270, 161, 31))
        self.btnHesapla.setAutoDefault(True)
        self.btnHesapla.setDefault(True)
        self.btnHesapla.setObjectName("btnHesapla")
        self.degerBoy = QtWidgets.QLineEdit(self.centralwidget)
        self.degerBoy.setGeometry(QtCore.QRect(140, 110, 71, 31))
        self.degerBoy.setObjectName("degerBoy")
        self.degerKilo = QtWidgets.QLineEdit(self.centralwidget)
        self.degerKilo.setGeometry(QtCore.QRect(140, 150, 71, 31))
        self.degerKilo.setObjectName("degerKilo")
        self.degerYas = QtWidgets.QLineEdit(self.centralwidget)
        self.degerYas.setGeometry(QtCore.QRect(140, 190, 71, 31))
        self.degerYas.setObjectName("degerYas")
        self.degerPAL = QtWidgets.QLineEdit(self.centralwidget)
        self.degerPAL.setGeometry(QtCore.QRect(140, 230, 71, 31))
        self.degerPAL.setObjectName("degerPAL")
        self.returnBKI = QtWidgets.QLabel(self.centralwidget)
        self.returnBKI.setGeometry(QtCore.QRect(50, 360, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.returnBKI.setFont(font)
        self.returnBKI.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.returnBKI.setObjectName("returnBKI")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 161, 51))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 133, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonKadin = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButtonKadin.setObjectName("radioButtonKadin")
        self.horizontalLayout_2.addWidget(self.radioButtonKadin)
        self.radioButtonErkek = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButtonErkek.setObjectName("radioButtonErkek")
        self.horizontalLayout_2.addWidget(self.radioButtonErkek)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setGeometry(QtCore.QRect(-10, -10, 281, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.layoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(430, 380, 271, 31))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_45.setFrameShape(QtWidgets.QFrame.Box)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_10.addWidget(self.label_45)
        self.returnPercentCHO = QtWidgets.QLabel(self.layoutWidget_8)
        self.returnPercentCHO.setFrameShape(QtWidgets.QFrame.Box)
        self.returnPercentCHO.setAlignment(QtCore.Qt.AlignCenter)
        self.returnPercentCHO.setObjectName("returnPercentCHO")
        self.horizontalLayout_10.addWidget(self.returnPercentCHO)
        self.returnPercentProtein = QtWidgets.QLabel(self.layoutWidget_8)
        self.returnPercentProtein.setFrameShape(QtWidgets.QFrame.Box)
        self.returnPercentProtein.setAlignment(QtCore.Qt.AlignCenter)
        self.returnPercentProtein.setObjectName("returnPercentProtein")
        self.horizontalLayout_10.addWidget(self.returnPercentProtein)
        self.returnPercentYag = QtWidgets.QLabel(self.layoutWidget_8)
        self.returnPercentYag.setFrameShape(QtWidgets.QFrame.Box)
        self.returnPercentYag.setAlignment(QtCore.Qt.AlignCenter)
        self.returnPercentYag.setObjectName("returnPercentYag")
        self.horizontalLayout_10.addWidget(self.returnPercentYag)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(710, 340, 131, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setObjectName("label_6")
        self.returnTotalCalorie = QtWidgets.QLabel(self.centralwidget)
        self.returnTotalCalorie.setGeometry(QtCore.QRect(710, 380, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.returnTotalCalorie.setFont(font)
        self.returnTotalCalorie.setFrameShape(QtWidgets.QFrame.Box)
        self.returnTotalCalorie.setText("")
        self.returnTotalCalorie.setObjectName("returnTotalCalorie")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 110, 71, 31))
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 150, 71, 31))
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 190, 71, 31))
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 230, 71, 31))
        self.label_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_10.setObjectName("label_10")
        self.groupDegisim = QtWidgets.QGroupBox(self.centralwidget)
        self.groupDegisim.setGeometry(QtCore.QRect(780, 100, 61, 231))
        self.groupDegisim.setTitle("")
        self.groupDegisim.setObjectName("groupDegisim")
        self.degisimYag = QtWidgets.QLineEdit(self.groupDegisim)
        self.degisimYag.setGeometry(QtCore.QRect(0, 200, 61, 31))
        self.degisimYag.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.degisimYag.setObjectName("degisimYag")
        self.degisimSut = QtWidgets.QLineEdit(self.groupDegisim)
        self.degisimSut.setGeometry(QtCore.QRect(0, 0, 61, 31))
        self.degisimSut.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.degisimSut.setObjectName("degisimSut")
        self.degisimEt = QtWidgets.QLineEdit(self.groupDegisim)
        self.degisimEt.setGeometry(QtCore.QRect(0, 40, 61, 31))
        self.degisimEt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.degisimEt.setObjectName("degisimEt")
        self.degisimSebze = QtWidgets.QLineEdit(self.groupDegisim)
        self.degisimSebze.setGeometry(QtCore.QRect(0, 120, 61, 31))
        self.degisimSebze.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.degisimSebze.setObjectName("degisimSebze")
        self.degisimMeyve = QtWidgets.QLineEdit(self.groupDegisim)
        self.degisimMeyve.setGeometry(QtCore.QRect(0, 160, 61, 31))
        self.degisimMeyve.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.degisimMeyve.setObjectName("degisimMeyve")
        self.degisimEYG = QtWidgets.QLineEdit(self.groupDegisim)
        self.degisimEYG.setGeometry(QtCore.QRect(0, 80, 61, 31))
        self.degisimEYG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.degisimEYG.setObjectName("degisimEYG")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(430, 60, 61, 31))
        self.label_49.setFrameShape(QtWidgets.QFrame.Box)
        self.label_49.setObjectName("label_49")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(320, 40, 20, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(380, 40, 20, 461))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(870, 40, 20, 461))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 40, 20, 461))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(30, 490, 301, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(30, 30, 301, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(390, 490, 491, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(390, 30, 491, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "ET"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "6"))
        self.label_14.setText(_translate("MainWindow", "5"))
        self.label_15.setText(_translate("MainWindow", "69"))
        self.label_16.setText(_translate("MainWindow", "SÜT"))
        self.label_17.setText(_translate("MainWindow", "9"))
        self.label_18.setText(_translate("MainWindow", "6"))
        self.label_19.setText(_translate("MainWindow", "6"))
        self.label_20.setText(_translate("MainWindow", "114"))
        self.label_21.setText(_translate("MainWindow", "EYG"))
        self.label_22.setText(_translate("MainWindow", "15"))
        self.label_23.setText(_translate("MainWindow", "2"))
        self.label_24.setText(_translate("MainWindow", "0"))
        self.label_25.setText(_translate("MainWindow", "68"))
        self.label_26.setText(_translate("MainWindow", "SEBZE"))
        self.label_27.setText(_translate("MainWindow", "6"))
        self.label_28.setText(_translate("MainWindow", "1"))
        self.label_29.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "28"))
        self.label_31.setText(_translate("MainWindow", "MEYVE"))
        self.label_32.setText(_translate("MainWindow", "12"))
        self.label_33.setText(_translate("MainWindow", "0"))
        self.label_34.setText(_translate("MainWindow", "0"))
        self.label_35.setText(_translate("MainWindow", "48"))
        self.label_36.setText(_translate("MainWindow", "YAĞ"))
        self.label_37.setText(_translate("MainWindow", "0"))
        self.label_38.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "5"))
        self.label_40.setText(_translate("MainWindow", "45"))
        self.label_41.setText(_translate("MainWindow", "KKAL"))
        self.returntotalCHO.setText(_translate("MainWindow", "0"))
        self.returntotalProtein.setText(_translate("MainWindow", "0"))
        self.returntotalYag.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "CHO"))
        self.label_2.setText(_translate("MainWindow", "Protein"))
        self.label_3.setText(_translate("MainWindow", "Yağ"))
        self.label_4.setText(_translate("MainWindow", "KKAL"))
        self.label_5.setText(_translate("MainWindow", "Değişim"))
        self.returnHarrisPAL.setText(_translate("MainWindow", "Harris Benedict: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Harris Benedict"))
        self.returnSchofield.setText(_translate("MainWindow", "Schofield:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Schofield"))
        self.returnWHO.setText(_translate("MainWindow", "WHO:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "WHO"))
        self.btnHesapla.setText(_translate("MainWindow", "Hesapla"))
        self.returnBKI.setText(_translate("MainWindow", "BKI: "))
        self.groupBox.setTitle(_translate("MainWindow", "Cinsiyet"))
        self.radioButtonKadin.setText(_translate("MainWindow", "Kadın"))
        self.radioButtonErkek.setText(_translate("MainWindow", "Erkek"))
        self.label_45.setText(_translate("MainWindow", "%"))
        self.returnPercentCHO.setText(_translate("MainWindow", "0"))
        self.returnPercentProtein.setText(_translate("MainWindow", "0"))
        self.returnPercentYag.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "   TOPLAM KALORİ"))
        self.label_7.setText(_translate("MainWindow", "Boy (cm):"))
        self.label_8.setText(_translate("MainWindow", "Kilo (kg):"))
        self.label_9.setText(_translate("MainWindow", "Yaş:"))
        self.label_10.setText(_translate("MainWindow", "PAL:"))
        self.degisimYag.setText(_translate("MainWindow", "0"))
        self.degisimSut.setText(_translate("MainWindow", "0"))
        self.degisimEt.setText(_translate("MainWindow", "0"))
        self.degisimSebze.setText(_translate("MainWindow", "0"))
        self.degisimMeyve.setText(_translate("MainWindow", "0"))
        self.degisimEYG.setText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "Porsiyon"))
